%% Example object-oriented communications workflow.

%% Create the waveform (a pulsed sine wave).
PSW = PulsedSineWave( "Amplitude", 2, ...
    "Phase", -pi/2, ...
    "PulseRate", 6, ...
    "Duration", 3, ...
    "Frequency", 800 );

%% Play back the waveform to be transmitted.
sound( PSW )

%% Create a transmitter and transmit the waveform.
T = Transmitter( "UpsamplingRate", 2e6, ...
    "CarrierFrequency", 6e5, ...
    "UpsamplingMethod", "resample" );
amWave = T.transmit( PSW );

%% Create a receiver and receive the waveform.
R = Receiver( "AttenuationFactor", 0.7, ...
    "CarrierFrequency", 6e5, ...
    "Delay", 25, ...
    "TargetSNR", 20, ...
    "DownsamplingFactor", 250, ...
    "DownsamplingMethod", "downsample" );
receivedWave = R.receive( amWave );

%% Play back the received waveform.
sound( receivedWave.PulsedSineWave, PSW.SampleRate )