% This test file was generated by Copilot. Validate generated output before use.
classdef tReceiver < matlab.unittest.TestCase
    methods(Test)
        function testConstructorWithDefaultValues(testCase)
            % Verify the receiver constructor initializes the documented defaults.
            receiver = Receiver();

            testCase.verifyEqual(receiver.AttenuationFactor, 0.8);
            testCase.verifyEqual(receiver.Delay, 23);
            testCase.verifyEqual(receiver.TargetSNR, 20);
            testCase.verifyEqual(receiver.CarrierFrequency, 6e5);
            testCase.verifyEqual(receiver.DownsamplingFactor, 250);
            testCase.verifyEqual(receiver.DownsamplingMethod, "downsample");
        end

        function testConstructorWithCustomValues(testCase)
            % Verify the receiver constructor accepts and stores custom property values.
            receiver = Receiver( ...
                AttenuationFactor = 0.5, ...
                Delay = 5, ...
                TargetSNR = 10, ...
                CarrierFrequency = 1e6, ...
                DownsamplingFactor = 10, ...
                DownsamplingMethod = "decimate");

            testCase.verifyEqual(receiver.AttenuationFactor, 0.5);
            testCase.verifyEqual(receiver.Delay, 5);
            testCase.verifyEqual(receiver.TargetSNR, 10);
            testCase.verifyEqual(receiver.CarrierFrequency, 1e6);
            testCase.verifyEqual(receiver.DownsamplingFactor, 10);
            testCase.verifyEqual(receiver.DownsamplingMethod, "decimate");
        end

        function testConstructorRejectsInvalidAttenuationFactor(testCase)
            % Verify invalid attenuation factors are rejected by property validation.
            testCase.verifyError( ...
                @() Receiver(AttenuationFactor = -0.1), ...
                "MATLAB:validators:mustBeInRange");
        end
    end
end