% This test file was generated by Copilot. Validate generated output before use.
classdef tTransmitter < matlab.unittest.TestCase
    methods(Test)
        function testDefaultConstruction(testCase)
            % Test that the default constructor creates an object with the documented defaults.
            transmitter = Transmitter();

            testCase.verifyEqual(transmitter.CarrierFrequency, 6e5);
            testCase.verifyEqual(transmitter.UpsamplingRate, 2e6);
            testCase.verifyEqual(transmitter.UpsamplingMethod, "resample");
        end

        function testConstructionWithCustomProperties(testCase)
            % Test that named arguments are applied during construction.
            transmitter = Transmitter( ...
                CarrierFrequency = 1.2e6, ...
                UpsamplingRate = 4e6, ...
                UpsamplingMethod = "interp");

            testCase.verifyEqual(transmitter.CarrierFrequency, 1.2e6);
            testCase.verifyEqual(transmitter.UpsamplingRate, 4e6);
            testCase.verifyEqual(transmitter.UpsamplingMethod, "interp");
        end

        function testInvalidCarrierFrequencyAssignment(testCase)
            % Test that an invalid carrier frequency is rejected by property validation.
            transmitter = Transmitter();

            testCase.verifyError(@() setInvalidCarrierFrequency(transmitter), ...
                "MATLAB:validators:mustBePositive");
        end

        function testInvalidUpsamplingMethodAssignment(testCase)
            % Test that an invalid upsampling method is rejected by property validation.
            transmitter = Transmitter();

            testCase.verifyError(@() setInvalidUpsamplingMethod(transmitter), ...
                "MATLAB:validators:mustBeMember");
        end

        function testTransmitProducesExpectedTimetable(testCase)
            % Test that transmit returns a timetable with the same variable name and more samples.
            originalTime = seconds((0:4).');
            originalSignal = sin(2*pi*50*double((0:4).')/1000);

            inputSignal = timetable(originalTime, originalSignal, ...
                "VariableNames", "Amplitude");
            inputSignal.Properties.SampleRate = 1000;

            wave = PulsedSineWave();
            wave.Signal = inputSignal;

            transmitter = Transmitter( ...
                CarrierFrequency = 1e5, ...
                UpsamplingRate = 4e3, ...
                UpsamplingMethod = "resample");

            transmittedWave = transmitter.transmit(wave);

            testCase.verifyClass(transmittedWave, "timetable");
            testCase.verifyEqual(transmittedWave.Properties.VariableNames, {"Amplitude"});
            testCase.verifyGreaterThanOrEqual(height(transmittedWave), height(inputSignal));
            testCase.verifyNotEmpty(transmittedWave.Properties.RowTimes);
        end
    end
end

function setInvalidCarrierFrequency(transmitter)
transmitter.CarrierFrequency = -1;
end

function setInvalidUpsamplingMethod(transmitter)
transmitter.UpsamplingMethod = "invalid";
end