% This test file was generated by Copilot. Validate generated output before use.
classdef tTransmitter < matlab.unittest.TestCase
    properties(TestParameter)
        TransmitMethod = struct( ...
            resample = "resample", ...
            upsample = "upsample", ...
            interp = "interp");
    end

    methods(Test)
        function testDefaultConstruction(testCase)
            % Test that the default constructor creates an object with the documented defaults.
            transmitter = Transmitter();

            testCase.verifyEqual(transmitter.CarrierFrequency, 6e5);
            testCase.verifyEqual(transmitter.UpsamplingRate, 2e6);
            testCase.verifyEqual(transmitter.UpsamplingMethod, "resample");
        end

        function testConstructionWithCustomProperties(testCase)
            % Test that named arguments are applied during construction.
            transmitter = Transmitter( ...
                CarrierFrequency = 1.2e6, ...
                UpsamplingRate = 4e6, ...
                UpsamplingMethod = "interp");

            testCase.verifyEqual(transmitter.CarrierFrequency, 1.2e6);
            testCase.verifyEqual(transmitter.UpsamplingRate, 4e6);
            testCase.verifyEqual(transmitter.UpsamplingMethod, "interp");
        end

        function testInvalidCarrierFrequencyAssignment(testCase)
            % Test that an invalid carrier frequency is rejected by property validation.
            transmitter = Transmitter();

            testCase.verifyError(@() setInvalidCarrierFrequency(transmitter), ...
                "MATLAB:validators:mustBePositive");
        end

        function testInvalidUpsamplingRateAssignment(testCase)
            % Test that an invalid upsampling rate is rejected by property validation.
            transmitter = Transmitter();

            testCase.verifyError(@() setInvalidUpsamplingRate(transmitter), ...
                "MATLAB:validators:mustBePositive");
        end

        function testNonfiniteUpsamplingRateAssignment(testCase)
            % Test that a nonfinite upsampling rate is rejected by property validation.
            transmitter = Transmitter();

            testCase.verifyError(@() setNonfiniteUpsamplingRate(transmitter), ...
                "MATLAB:validators:mustBeFinite");
        end

        function testInvalidUpsamplingMethodAssignment(testCase)
            % Test that an invalid upsampling method is rejected by property validation.
            transmitter = Transmitter();

            testCase.verifyError(@() setInvalidUpsamplingMethod(transmitter), ...
                "MATLAB:validators:mustBeMember");
        end

        function testTransmitPreservesMetadataAndTimeSpan(testCase, TransmitMethod)
            % Test that each upsampling branch produces a valid modulated timetable.
            wave = createSilentWave();
            inputSignal = wave.Signal;
            transmitter = Transmitter( ...
                CarrierFrequency = 10, ...
                UpsamplingRate = 2000, ...
                UpsamplingMethod = TransmitMethod);

            transmittedSignal = transmit(transmitter, wave);

            testCase.verifyEqual(height(transmittedSignal), 22);
            testCase.verifyEqual(transmittedSignal.Properties.VariableNames, ...
                inputSignal.Properties.VariableNames);
            testCase.verifyEqual(transmittedSignal.Time(1), inputSignal.Time(1));
            testCase.verifyEqual(transmittedSignal.Time(end), inputSignal.Time(end));
            testCase.verifySize(transmittedSignal.PulsedSineWave, [22 1]);
            testCase.verifyTrue(all(isfinite(transmittedSignal.PulsedSineWave)));
        end

    end
end

function setInvalidCarrierFrequency(transmitter)
transmitter.CarrierFrequency = -1;
end

function setInvalidUpsamplingRate(transmitter)
transmitter.UpsamplingRate = 0;
end

function setNonfiniteUpsamplingRate(transmitter)
transmitter.UpsamplingRate = Inf;
end

function setInvalidUpsamplingMethod(transmitter)
transmitter.UpsamplingMethod = "invalid";
end

function wave = createSilentWave()
wave = PulsedSineWave( ...
    Amplitude = 0, ...
    Frequency = 0, ...
    Duration = 0.01, ...
    PulseRate = 1, ...
    Duty = 100, ...
    SampleRate = 1000);
end
